from typing import Protocol

from .models import Dispatch, IssueKey, RunObservation, ValidationResult


class AgentAdapter(Protocol):
    def create(self, dispatch: Dispatch) -> str: ...
    def start(self, dispatch: Dispatch) -> None: ...
    def observe(self, dispatch: Dispatch) -> RunObservation: ...
    def stop(self, dispatch: Dispatch, *, cancel: bool) -> None: ...
    def resume(self, dispatch: Dispatch) -> None: ...


class Delivery(Protocol):
    def capture(self, dispatch: Dispatch) -> str: ...
    def validate(self, candidate_sha: str, profile: str) -> ValidationResult: ...
    def publish(self, issue: IssueKey, candidate_sha: str) -> str: ...
